const ARABIC_TEXT: Readonly<Record<string, string>> = {
  'Faisal Al Qahtani': 'فيصل القحطاني',
  'Asir Adventures Co.': 'شركة مغامرات عسير',
  'Jabal Sawda': 'جبل السودة',
  Habala: 'الحبلة',
  'Old Abha': 'أبها القديمة',
  'Wadi Mahala': 'وادي محالة',
  Soudah: 'السودة',
  'Rijal Almaa': 'رجال ألمع',
  Abha: 'أبها',
  Asir: 'عسير',
  'Before dawn': 'قبل الفجر',
  Sunrise: 'الشروق',
  'Late afternoon': 'آخر العصر',
  Evening: 'المساء',
  Night: 'الليل',
  Midday: 'منتصف النهار',
  Afternoon: 'بعد الظهر',
  Morning: 'الصباح',
  'Late morning': 'أواخر الصباح',
  'Local guide': 'مرشد محلي',
  'Asiri breakfast': 'فطور عسيري',
  'Hot qahwa': 'قهوة ساخنة',
  'Warm layer': 'ملابس دافئة',
  'Walking shoes': 'حذاء مناسب للمشي',
  'Traditional dinner': 'عشاء تقليدي',
  'Live Asiri music': 'موسيقى عسيرية حية',
  'Tea and qahwa': 'شاي وقهوة',
  Appetite: 'شهية مفتوحة',
  'A light jacket for the evening': 'سترة خفيفة للمساء',
  'Coffee workshop': 'ورشة قهوة',
  'Saleeg lunch': 'غداء سليق',
  'Recipe card': 'بطاقة وصفة',
  'Guided session': 'جلسة موجهة',
  Mat: 'بساط',
  'Herbal tea': 'شاي أعشاب',
  'Comfortable clothing': 'ملابس مريحة',
  'Certified guide': 'مرشد معتمد',
  'Harness and helmet': 'حزام وخوذة',
  Insurance: 'تأمين',
  'Closed shoes': 'حذاء مغلق',
  Water: 'ماء',
  'All materials': 'كل المواد',
  'Artist instruction': 'إرشاد من الفنانة',
  'Panel to take home': 'لوحة تأخذها معك',
  'Clothes that can get paint on them': 'ملابس لا تمانع اتساخها بالطلاء',
  'Free cancellation up to 48 hours before the experience.': 'إلغاء مجاني حتى 48 ساعة قبل التجربة.',
  'Free cancellation up to 72 hours before the experience.': 'إلغاء مجاني حتى 72 ساعة قبل التجربة.',
  'Free cancellation up to 24 hours before the experience.': 'إلغاء مجاني حتى 24 ساعة قبل التجربة.',
  'Free cancellation up to 72 hours before; weather reschedules are free.':
    'إلغاء مجاني حتى 72 ساعة قبل التجربة، وإعادة الجدولة بسبب الطقس مجانية.',
};

export function toArabicText(text: string): string {
  return ARABIC_TEXT[text] ?? text;
}
